### ISSUE TITLE
Ошибка при установке приватнго ключа

### ISSUE THREAD

**Issue by Blizjke** [20th/kkb_epay#3]
Добрый день при установке приватного ключа возникла ошибка:
Key is not valid, it does not contain a correct RSA key declaration.
There is something wrong with this key. Please check that the provided information is correct.
С чем это может быть связано? ключи получены недавно.

**Comment by 20th** [comment]
В последнее время казком генерирует немного другие ключи, чем раньше. Попробуйте использовать последную версию модуля из master-ветки:

https://github.com/20th/kkb_epay/archive/7.x-1.x.zip

**Comment by Blizjke** [comment]
Выдает вот такую ошибку при 
KkbEpay_KeyException: Private key does not exist as a system variable. в функции KkbEpay_DrupalKeyLoader->loadKeyData() (строка 61 в файле ../sites/default/modules/kkb_epay/includes/classes/KkbEpay_DrupalKeyLoader.php).
в settings.php все что надо было добавил.
В чем может быть проблема?

**Comment by Blizjke** [comment]
Большое спасибо, все идаельно работает!
